import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import xooth_logo from "../Asset/xooth_logo.png"
import axios from 'axios';
import { CgFacebook } from "react-icons/cg";
import { FaXTwitter, FaInstagram } from "react-icons/fa6";

function Home() {
  const [postNews, setPostNews] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [techNews, setTechNews] = useState(null);

  const newsPerPage = 3;

  // Fetch Breaking News
  useEffect(() => {
    const getNews = async () => {
      try {
        const result = await axios.get("https://xooth-backend.onrender.com/api/getNews");
        setPostNews(result.data.data || []);
      } catch (error) {
        console.error("Error fetching news:", error);
      }
    };
    getNews();
  }, []);

  // Fetch Tech News
  useEffect(() => {
    const fetchTechNews = async () => {
      try {
        const response = await axios.get('https://xooth-backend.onrender.com/api/TechnologyNews');
        const data = response.data;
        if (data.length > 0) {
          setTechNews(data[0]);
        }
      } catch (error) {
        console.error('Error fetching tech news:', error);
      }
    };
    fetchTechNews();
  }, []);

  // Pagination
  const indexOfLastNews = currentPage * newsPerPage;
  const indexOfFirstNews = indexOfLastNews - newsPerPage;
  const currentNews = postNews.slice(indexOfFirstNews, indexOfLastNews);

  const handleNextNewsPage = () => {
    if (currentPage < Math.ceil(postNews.length / newsPerPage)) {
      setCurrentPage(currentPage + 1);
    }
  };

  const handlePreviousNewsPage = () => {
    if (currentPage > 1) {
      setCurrentPage(currentPage - 1);
    }
  };

  // Loader for tech news
  if (!techNews) {
    return <div className='text-center mt-[15rem]'>Loading...</div>;
  }

  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-[rgb(2,2,39)] text-white p-4 flex justify-between items-center">
        <Link to="/" className="text-2xl font-bold">
          <img src={xooth_logo} alt="xooth" className="w-12"/>
       </Link>
         <nav>
        <Link to="/" className="text-white hover:underline">
           Home
       </Link>
        </nav>
     </header>

      <div className="w-[100%] flex flex-col lg:flex-row">
        <div className="w-[100%] lg:w-[50%]">
          <section>
            <div>
              {postNews.length === 0 ? (
                <h1 className="font-bold text-5xl p-4">No Breaking News Yet</h1>
              ) : (
                <div className="mx-auto">
                  <h1 className="font-bold text-5xl p-4">Breaking News</h1>
                  <ul>
                    {currentNews.map((newsItem, index) => (
                      <li key={index} className="p-2">
                        <h2 className="font-bold text-2xl p-2 cursor-pointer">
                          <Link to={`/news/${newsItem._id}`}>
                            <img
                              src={newsItem.image}
                              alt={newsItem.news_headline}
                              className="w-full xl:w-[65%] h-auto cursor-pointer"
                            />
                          </Link>
                        </h2>
                        <h2 className="cursor-pointer font-semibold text-sm xl:w-[65%] w-[100%] text-justify hover:text-slate-700">
                          <Link to={`/news/${newsItem._id}`}>
                            {newsItem.news_headline}
                          </Link>
                          <br />
                          <i>generated by AI</i>
                        </h2>
                        <p className="text-sm p-2">
                          {`Published on: ${new Date(newsItem.time).toLocaleString()}`}
                        </p>
                      </li>
                    ))}
                  </ul>

                  <div className="pagination flex justify-center mt-4">
                    {currentPage > 1 && (
                      <button onClick={handlePreviousNewsPage} className="mx-2 px-4 py-2 bg-gray-300">
                        Previous
                      </button>
                    )}
                    {currentPage < Math.ceil(postNews.length / newsPerPage) && (
                      <button onClick={handleNextNewsPage} className="mx-2 px-4 py-2 bg-gray-300">
                        Next
                      </button>
                    )}
                  </div>
                </div>
              )}
            </div>
          </section>
        </div>

        <div className='xl:w-[70%]'>
          <p className='xl:text-4xl font-bold p-5'>{techNews.news_headline}</p>
          {techNews.image && (
            <img
              src={techNews.image}
              alt={techNews.news_headline}
              className='xl:w-[100%]'
            />
          )}
          <i className='mt-[3rem] block px-5'>{techNews.content}</i>
        </div>
      </div>

      <footer className="w-full mt-10">
        <div className='flex-col md:lg:xl:flex-row space-y-10 xl:space-y-0 ml-[7rem] xl:ml-0'>
          <div>
            <h1 className="text-[#ffff] font-bold xl:text-4xl text-xl mt-4 xl:mt-0">XOOTH</h1>
            <p className='font-light text-center'>Connect effortlessly with xooth</p>
          </div>

          <div className='flex gap-2 xl:text-3xl text-xl font-bold xl:ml-8'>
            <CgFacebook className='cursor-pointer' />
            <FaXTwitter className='cursor-pointer' />
            <FaInstagram className='cursor-pointer' />
          </div>
        </div>
      </footer>
    </div>
  );
}

export default Home;
